import { assert } from 'chai';
import postSize from '../public/assets/post_size.js';

describe('Функция проверки расчета размера поста', function () {
  it('без ссылок', function () {
    let expectedResult = 12;
    let result = postSize('Всем привет!');
    assert.equal(expectedResult, result);
    expectedResult = 8;
    result = postSize('Привет! https://google.com');
    assert.equal(expectedResult, result);
    expectedResult = 39;
    result = postSize('Привет! vk.ru ссылка на страницу "ВКонтакте"');
    assert.equal(expectedResult, result);
    expectedResult = 27;
    result = postSize('Чтобы перевести текст translate.google.com/?hl=ru или reverso.net');
    assert.equal(expectedResult, result);
    expectedResult = 44;
    result = postSize('Смотрите прямые эфиры телеканалов России на https://limehd.tv/tv');
    assert.equal(expectedResult, result);
    expectedResult = 52;
    result = postSize('Обзоры и рейтинг лучших регистраторов доменных имен ru.hostings.info');
    assert.equal(expectedResult, result);
    expectedResult = 28;
    result = postSize('История доменной зоны SU на https://sm.su/blog/domain/7514/');
    assert.equal(expectedResult, result);
    expectedResult = 70;
    result = postSize('Интерактивный сервис прямых трансляций для самого разного контента на twitch.tv');
    assert.equal(expectedResult, result);
    expectedResult = 30;
    result = postSize('Домены film.movie developer.pro выставлены на продажу');
    assert.equal(expectedResult, result);
    expectedResult = 25;
    result = postSize('Сайт с на японском языке www.turkleriz.biz');
    assert.equal(expectedResult, result);
    expectedResult = 43;
    result = postSize('Посмотреть результаты футбольных матчей на www.soccer.ru');
    assert.equal(expectedResult, result);
  });
});
